server:
  port: 8280
  context-path: /

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_jxc2?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
     database-platform: org.hibernate.dialect.MySQLDialect
   thymeleaf:
    cache: false
   servlet:
    multipart:
      max-file-size: 521MB
      max-request-size: 1024MB
      enabled: true
      resolve-lazily: false